
project_id = "jzmzmjvtxcrxljnhhrjo"

[[functions.function]]
name = "send-email"
verify_jwt = false

[[functions.function]]
name = "send-daily-report"
verify_jwt = false

[[functions.function]]
name = "send-resend-report"
verify_jwt = false

[[functions.function]]
name = "send-company-email"
verify_jwt = false

[[functions.function]]
name = "send-test-report"
verify_jwt = false

[[functions.function]]
name = "notify-admin"
verify_jwt = false

[functions]
port = 9999
